services:
  # Conteneur Ollama (serveur IA local)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434" # expose l’API locale
    volumes:
      - ollama_models:/root/.ollama # stockage persistant des modèles
    restart: unless-stopped

  # Conteneur Python (ton pipeline)
  jsonformater:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    container_name: jsonformater
    volumes:
      - ./jsons:/app/jsons
      - ./python:/app/python
      - ./docs:/app/docs
      - ./context:/app/context
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    tty: true

volumes:
  ollama_models:
